import { defineConfig, type Plugin } from 'vite';
import { viteSingleFile } from 'vite-plugin-singlefile';
import { fileURLToPath } from 'node:url';
import { readFileSync } from 'node:fs';

/** Emits sw.js with a precache list of every built asset (full offline play after first load). */
function serviceWorker(): Plugin {
  return {
    name: 'blockforge-sw',
    apply: 'build',
    generateBundle(_opts, bundle) {
      const files = Object.keys(bundle).filter((f) => !f.endsWith('.map'));
      const precache = ['./', ...files.map((f) => './' + f), './favicon.svg', './manifest.webmanifest', './icon-192.png', './icon-512.png'];
      const version = Date.now().toString(36);
      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: `// Generated by vite.config.ts — BlockForge offline cache.
const CACHE = 'blockforge-${version}';
const PRECACHE = ${JSON.stringify(precache)};
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  if (req.mode === 'navigate') {
    e.respondWith(fetch(req).then((res) => { const copy = res.clone(); caches.open(CACHE).then((c) => c.put('./', copy)); return res; }).catch(() => caches.match('./')));
    return;
  }
  e.respondWith(caches.match(req).then((hit) => hit || fetch(req)));
});
`,
      });
    },
  };
}

/** Single-file mode: inline the favicon and drop links to files that won't exist. */
function singleFileHtml(): Plugin {
  return {
    name: 'blockforge-single-html',
    transformIndexHtml(html) {
      const svg = readFileSync(fileURLToPath(new URL('./public/favicon.svg', import.meta.url)), 'utf8');
      const uri = 'data:image/svg+xml,' + encodeURIComponent(svg);
      return html
        .replace(/<link rel="icon"[^>]*>/, `<link rel="icon" type="image/svg+xml" href="${uri}" />`)
        .replace(/\s*<link rel="manifest"[^>]*>/, '')
        .replace(/\s*<link rel="apple-touch-icon"[^>]*>/, '');
    },
  };
}

export default defineConfig(({ mode }) => {
  const single = mode === 'single';
  return {
    base: './',
    // The single file is often opened straight from disk (file://, opaque origin), where Chrome refuses
    // module workers from blob URLs; a classic (IIFE) worker loads fine there.
    worker: { format: single ? 'iife' : 'es' },
    define: { __SINGLE_FILE__: JSON.stringify(single) },
    resolve: single
      ? { alias: [{ find: /^\.\/workerFactory$/, replacement: fileURLToPath(new URL('./src/world/workerFactory.inline.ts', import.meta.url)) }] }
      : undefined,
    plugins: single ? [singleFileHtml(), viteSingleFile({ removeViteModuleLoader: true })] : [serviceWorker()],
    publicDir: single ? false : 'public',
    build: {
      target: 'es2022',
      chunkSizeWarningLimit: 1200,
      outDir: single ? 'dist-single' : 'dist',
      emptyOutDir: true,
    },
    test: { environment: 'node', include: ['tests/**/*.test.ts'] },
  } as never;
});
