import { chromium } from 'playwright';
const url = process.env.URL || 'http://localhost:4173/';
const browser = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errors = [];
page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') errors.push(`[${m.type()}] ${m.text()}`); });
page.on('pageerror', (e) => errors.push('[pageerror] ' + e.message));
page.on('requestfailed', (r) => errors.push('[reqfail] ' + r.url()));
await page.goto(url);
await page.waitForSelector('[data-screen=menu]');
await page.waitForTimeout(500);
await page.screenshot({ path: 'qa-output/01-menu.png' });
await page.click('[data-act=new]');
await page.fill('[name=seed]', 'forge');
await page.screenshot({ path: 'qa-output/02-new.png' });
await page.click('[data-act=create]');
const t0 = Date.now();
await page.waitForFunction(() => window.__bf?.state === 'playing', null, { timeout: 90000 });
console.log('load ms', Date.now() - t0);
await page.waitForTimeout(3000);
await page.screenshot({ path: 'qa-output/03-game.png' });
const info = await page.evaluate(() => { const g = window.__bf.app.game; return { pos: [g.player.body.x, g.player.body.y, g.player.body.z], stats: g.world.stats() }; });
console.log(JSON.stringify(info));
console.log(errors.join('\n'));
await browser.close();
